'\" t
.\"     Title: laby
.\"    Author: Mehdi Dogguy <dogguy@pps.jussieu.fr>
.\" Generator: DocBook XSL Stylesheets v1.75.0 <http://docbook.sf.net/>
.\"      Date: May 13, 2009
.\"    Manual: Games
.\"    Source: laby
.\"  Language: English
.\"
.TH "LABY" "6" "May 13, 2009" "laby" "Games"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
laby \- Learn programming playing with ants and spider webs
.SH "SYNOPSIS"
.HP \w'\fBlaby\fR\ 'u
\fBlaby\fR [options]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBlaby\fR
command\&.
.PP
In this game, you will have to move an ant out of a labyrinth, avoid spider webs, move rocks, etc\&.\&.\&. You have to click on "Reload" at startup\&.
.SH "OPTIONS"
.PP
\fB\-\-help\fR
.RS 4
Display help message
.RE
.PP
\fB\-\-version\fR
.RS 4
Show versioning information
.RE
.PP
\fB\-\-lang=\fRl
.RS 4
Select a programming language
.RE
.PP
\fB\-\-sound\fR
.RS 4
Enable/Disable sounds
.RE
.PP
\fB\-\-tile\-size=\fRn
.RS 4
Set tile\'s size in pixels
.RE
.PP
\fB\-\-conf\fR
.RS 4
Set a configuration key
.RE
.PP
\fB\-\-conf\-descr=\fRkey
.RS 4
Describe a configuration key
.RE
.PP
\fB\-\-conf\-dump\fR
.RS 4
Dump a configutation key
.RE
.PP
\fB\-\-debug=\fRd
.RS 4
Select debug level where d is an integer
.RE
.SH "LICENSE"
.PP
This manual page was written by
Mehdi Dogguy
dogguy@pps\&.jussieu\&.fr
for the Debian GNU/Linux system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 3 or any later version published by the Free Software Foundation; considering as source code all the file that enable the production of this manpage\&.
.SH "AUTHOR"
.PP
\fBMehdi Dogguy\fR <\&dogguy@pps\&.jussieu\&.fr\&>
.RS 4
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2009 Mehdi Dogguy
.br
